DROP TABLE [LA_QUERY_DE_PAPEL].[FuncionalidadxRol]
DROP TABLE [LA_QUERY_DE_PAPEL].[Funcionalidad]
DROP TABLE [LA_QUERY_DE_PAPEL].[Factura]
DROP TABLE [LA_QUERY_DE_PAPEL].[Consumible]
DROP TABLE [LA_QUERY_DE_PAPEL].[UsuarioxHotel]
DROP TABLE [LA_QUERY_DE_PAPEL].[ReservaxHabitacion]
DROP TABLE [LA_QUERY_DE_PAPEL].[Reserva]
DROP TABLE [LA_QUERY_DE_PAPEL].[RegimenxHotel]
DROP TABLE [LA_QUERY_DE_PAPEL].[Regimen]
DROP TABLE [LA_QUERY_DE_PAPEL].[Habitacion]
DROP TABLE [LA_QUERY_DE_PAPEL].[Hotel_Baja]
DROP TABLE [LA_QUERY_DE_PAPEL].[Hotel]
DROP TABLE [LA_QUERY_DE_PAPEL].[Cliente]
DROP TABLE [LA_QUERY_DE_PAPEL].[Usuario]
DROP TABLE [LA_QUERY_DE_PAPEL].[Persona]
DROP TABLE [LA_QUERY_DE_PAPEL].[Persona_conflicto_migracion]
DROP TABLE [LA_QUERY_DE_PAPEL].[Rol]

DROP TRIGGER LA_QUERY_DE_PAPEL.insertUsuarios
DROP TRIGGER LA_QUERY_DE_PAPEL.deleteUsuarios
DROP TRIGGER LA_QUERY_DE_PAPEL.updateUsuarios
DROP TRIGGER LA_QUERY_DE_PAPEL.deletePersonas

DROP VIEW LA_QUERY_DE_PAPEL.usuarios

DROP PROCEDURE LA_QUERY_DE_PAPEL.procedure_login
